#!/bin/bash

set -e
cd *

# Suspend CC and CFLAGS
TMP_CC=$CC
TMP_CFLAGS=$CFLAGS
unset CC
unset CFLAGS

# Compile tic
mkdir build
cd build
../configure
make -C include
make -C progs tic
cd ..

# Restore CC and CFLAGS
export CC=$TMP_CC
export CFLAGS=$TMP_CFLAGS
unset TMP_CC
unset TMP_CFLAGS

# Compile ncurses
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST \
	--mandir=/usr/share/man \
	--with-manpage-format=normal \
	--with-shared \
	--without-debug \
	--without-ada \
	--without-normal \
	--enable-widec
make -j${JOBS}

# Install
make DESTDIR=$SYSROOT TIC_PATH=$(pwd)/build/progs/tic install
echo "INPUT(-lncursesw)" >$SYSROOT/usr/lib/libncurses.so
