#!/bin/bash

set -e

# TODO Add a feature in the package builder to unwrap the directories automatically
cd $(ls -1d ncurses*)

# Patching to support Maestro
sed -i 's/^	gnu\* |/	gnu* | maestro* |/' config.sub

# Patching to ensure gawk is found first
sed -i s/mawk// configure

# Suspending CC and CFLAGS
TMP_CC=$CC
TMP_CFLAGS=$CFLAGS
unset CC
unset CFLAGS

# Compiling tic
mkdir build
cd build
../configure
make -C include
make -C progs tic
cd ..

# Restoring CC and CFLAGS
export CC=$TMP_CC
export CFLAGS=$TMP_CFLAGS
unset TMP_CC
unset TMP_CFLAGS

# Compiling ncurses
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST \
	--mandir=/usr/share/man \
	--with-manpage-format=normal \
	--with-shared \
	--without-debug \
	--without-ada \
	--without-normal \
	--enable-widec
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT TIC_PATH=$(pwd)/build/progs/tic install
echo "INPUT(-lncursesw)" >$SYSROOT/usr/lib/libncurses.so
