#!/bin/bash

set -e



# Compiling
cargo build --target $TARGET -Zbuild-std --release



# Installing
mkdir -p $SYSROOT/sbin
# TODO Iterate on all executables
cp target/$TARGET/release/dmesg $SYSROOT/sbin
cp target/$TARGET/release/fdisk $SYSROOT/sbin
cp target/$TARGET/release/insmod $SYSROOT/sbin
cp target/$TARGET/release/login $SYSROOT/sbin
cp target/$TARGET/release/lsmod $SYSROOT/sbin
cp target/$TARGET/release/mkfs $SYSROOT/sbin
cp target/$TARGET/release/mount $SYSROOT/sbin
cp target/$TARGET/release/nologin $SYSROOT/sbin
cp target/$TARGET/release/powerctl $SYSROOT/sbin
cp target/$TARGET/release/ps $SYSROOT/sbin
cp target/$TARGET/release/rmmod $SYSROOT/sbin
cp target/$TARGET/release/su $SYSROOT/sbin
cp target/$TARGET/release/umount $SYSROOT/sbin
cp target/$TARGET/release/usrgrp $SYSROOT/sbin

ln -s /sbin/fdisk $SYSROOT/sbin/sfdisk
ln -s /sbin/mkfs $SYSROOT/sbin/mkfs.ext2
ln -s /sbin/powerctl $SYSROOT/sbin/halt
ln -s /sbin/powerctl $SYSROOT/sbin/reboot
ln -s /sbin/powerctl $SYSROOT/sbin/shutdown
ln -s /sbin/powerctl $SYSROOT/sbin/suspend
ln -s /sbin/usrgrp $SYSROOT/sbin/useradd
ln -s /sbin/usrgrp $SYSROOT/sbin/userdel
ln -s /sbin/usrgrp $SYSROOT/sbin/usermod
ln -s /sbin/usrgrp $SYSROOT/sbin/groupadd
ln -s /sbin/usrgrp $SYSROOT/sbin/groupdel
ln -s /sbin/usrgrp $SYSROOT/sbin/groupmod
