[package]
name = "maestro-utils"
version = "0.1"
description = "Maestro-utils is a package of utility commands for the Maestro OS"

[[source]]
location = "/"
git_url = "https://github.com/maestro-os/maestro-utils"