#!/bin/bash

set -e

# Patching to support Maestro
sed -i 's/^	-gnu\* |/	-gnu* | -maestro* |/' config/config.sub

# Compiling
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT install
ln -s bash $SYSROOT/usr/bin/sh
