[package]
name = "xorg-server"
version = "21.1.21"
description = "The X.Org project provides an open source implementation of the X Window System."

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/xserver/xorg-server-21.1.21.tar.xz"