[package]
name = "xorg-server"
version = "21.1.21"
description = "The X.Org project provides an open source implementation of the X Window System."

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/xserver/xorg-server-21.1.21.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "libx11"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxcb"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxfont2"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxkbfile"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxcvt"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libpciaccess"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "pixman"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "encodings"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "font-alias"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "font-misc-misc"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "font-cursor-misc"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xkeyboard-config"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xkbcomp"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "findutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
