#!/bin/bash

set -e

# Compiling
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST \
	--disable-static \
	--docdir=/usr/share/doc/xz-5.2.5
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT install
