[package]
name = "xz"
version = "5.8.1"
description = "XZ Utils is free general-purpose data compression software with a high compression ratio"

[[source]]
location = "/"
url = "https://netcologne.dl.sourceforge.net/project/lzmautils/xz-5.8.1.tar.xz?viasf=1"
