#!/bin/bash

set -e



# Creating configuration
# TODO Adapt arch to TARGET
cat >.config <<EOF
general_arch="x86"
general_scheduler_end_panic="true"
debug_debug="false"
debug_test="false"
debug_testprocess="false"
debug_storagetest="false"
debug_qemu="false"
debug_malloc_magic="false"
debug_malloc_check="false"
debug_rust_backtrace="false"
EOF



# Compiling
make



# Installing
mkdir -p $SYSROOT/boot
cp maestro $SYSROOT/sbin/init

# TODO Add grub entry
