#!/bin/bash

set -e

# Patching to support Maestro
sed -i 's/^	gnu\* |/	gnu* | maestro* |/' build-aux/config.sub

./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST
make -j${JOBS}
make DESTDIR=$SYSROOT install
