#!/bin/bash

set -e

# TODO Add a feature in the package builder to unwrap the directories automatically
cd $(ls -1d m4*)

# Patching to support Maestro
sed -i 's/^	gnu\* |/	gnu* | maestro* |/' build-aux/config.sub

./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST
make -j${JOBS}
make DESTDIR=$SYSROOT install
