#!/bin/bash

set -e
cd *

./configure \
	--prefix=/usr \
	--disable-static \
	--host=$HOST \
	--docdir="/usr/share/doc/pkgconf-$VERSION"

make -j${JOBS}
make DESTDIR="$INSTALL_PATH" install

ln -sv pkgconf "$INSTALL_PATH/usr/bin/pkg-config"
ln -sv pkgconf.1 "$INSTALL_PATH/usr/share/man/man1/pkg-config.1"