#!/bin/bash

set -e

cargo +nightly build --target $HOST -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort --release

mkdir -p $INSTALL_PATH/sbin
mkdir -p $INSTALL_PATH/etc/solfege/services

cat >$INSTALL_PATH/etc/fstab <<EOF
# <file system> <dir> <type> <options> <dump> <pass>
tmpfs			/tmp	tmpfs	rw		0		0
procfs			/proc	procfs	rw		0		1
EOF
ln -sv /proc/self/mounts $INSTALL_PATH/etc/mtab

echo '/sbin/login' >$INSTALL_PATH/etc/solfege/startup

cp target/$HOST/release/solfege $INSTALL_PATH/sbin/init
