#!/bin/bash

set -e



# Build
cargo +nightly build --target $TARGET -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort --release



# Install
mkdir -p $SYSROOT/sbin
mkdir -p $SYSROOT/etc/solfege/services

cat >$SYSROOT/etc/fstab <<EOF
# <file system> <dir> <type> <options> <dump> <pass>
tmpfs			/tmp	tmpfs	rw		0		0
procfs			/proc	procfs	rw		0		1
EOF
ln -sv /proc/self/mounts $SYSROOT/etc/mtab

echo '/sbin/login' >$SYSROOT/etc/solfege/startup

cp target/$TARGET/release/solfege $SYSROOT/sbin/init
