#!/bin/bash

set -e

# Build
# FIXME: compilation of panic_abort is required only because of a Cargo bug. remove when fixed
cargo +nightly build --target $TARGET -Zbuild-std=std,panic_abort -Zbuild-std-features=panic_immediate_abort --release

# Install
mkdir -p $SYSROOT/usr/bin
# TODO Iterate on all executables
cp target/$TARGET/release/ping $SYSROOT/usr/bin
