#!/bin/bash

set -e

# Build
cargo +nightly build --target x86_64-unknown-linux-musl -Zbuild-std=std,panic_abort --release

# Install
mkdir -p $INSTALL_PATH/usr/bin
# TODO Iterate on all executables
cp target/$HOST/release/ping $INSTALL_PATH/usr/bin
