[package]
name = "libxfont2"
version = "2.0.7"
description = "X font handling library for server side"

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/lib/libXfont2-2.0.7.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xorgproto"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xtrans"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libfontenc"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "freetype"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
