[package]
name = "bzip2"
version = "1.0.8"
description = "bzip2 is a freely available, patent free, high-quality data compressor."

[[source]]
location = "/"
url = "https://www.sourceware.org/pub/bzip2/bzip2-1.0.8.tar.gz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "diffutils"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
