#!/bin/bash

set -e
cd *

# Compile
echo '#define SYS_VIMRC_FILE  "/etc/vimrc"' >>src/feature.h
echo '#define SYS_GVIMRC_FILE "/etc/gvimrc"' >>src/feature.h
./configure \
			--prefix=/usr        \
			--host=$TARGET       \
			--with-features=huge \
			--enable-gui=gtk3    \
			--with-tlib=ncursesw
make -j${JOBS}

# Install
make DESTDIR=$SYSROOT install
