#!/bin/bash

set -e
cd *

echo '#define SYS_VIMRC_FILE  "/etc/vimrc"' >>src/feature.h
echo '#define SYS_GVIMRC_FILE "/etc/gvimrc"' >>src/feature.h
./configure \
			--prefix=/usr        \
			--host=$HOST         \
			--with-features=huge \
			--enable-gui=gtk3    \
			--with-tlib=ncursesw
make -j${JOBS}

make DESTDIR=$INSTALL_PATH install
