#!/bin/bash

set -e
cd *

if [ ! -z "$CC" ]; then
	export CC="$CC $CFLAGS"
	unset CFLAGS
fi
if [ ! -z "$LD" ]; then
	export LD="$LD $LDFLAGS"
	unset LDFLAGS
fi

./configure           \
	--target=$TARGET  \
	--host=$HOST      \
	--prefix=/usr     \
	--sysconfdir=/etc \
	--disable-efiemu  \
	--disable-werror
make -j${JOBS}

make DESTDIR=$SYSROOT install
