#!/bin/bash

set -e
unset CC CFLAGS LD LDFLAGS RUSTFLAGS

PROFILE=release /usr/src/maestro/mod/build

# TODO support several targets
# TODO get version from selected kernel dependency?
mkdir -pv $INSTALL_PATH/lib/modules/maestro-0.1.0/default
cp -v target/x86/release/libps2.so $INSTALL_PATH/lib/modules/maestro-0.1.0/default/ps2.kmod
