#!/bin/bash

set -e

PROFILE=release /usr/src/maestro/mod/compile ps2

# TODO get version from selected kernel dependency?
mkdir -pv $SYSROOT/lib/modules/maestro-1.0/default
cp -v ps2.kmod $SYSROOT/lib/modules/maestro-1.0/default/
