[package]
name = "libxi"
version = "1.8.3"
description = "X Input Extension library"

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/lib/libXi-1.8.3.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libx11"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxext"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxfixes"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xorgproto"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
