#!/bin/bash

set -e
cd *

# Maestro has no udev, patch. All udev use in src/evdev.c is guarded
# by `#ifdef HAVE_LIBUDEV`, so with libudev absent nothing links -ludev.
patch -p1 <<'PATCH_EOF'
--- a/configure
+++ b/configure
@@ -19386,31 +19386,11 @@
         # Put the nasty error message in config.log where it belongs
         echo "$UDEV_PKG_ERRORS" >&5
 
-        as_fn_error $? "Package requirements (libudev) were not met:
-
-$UDEV_PKG_ERRORS
-
-Consider adjusting the PKG_CONFIG_PATH environment variable if you
-installed software in a non-standard prefix.
-
-Alternatively, you may set the environment variables UDEV_CFLAGS
-and UDEV_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details." "$LINENO" 5
+	: # libudev optional (Maestro has no udev)
 elif test $pkg_failed = untried; then
         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
 printf "%s\n" "no" >&6; }
-        { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: error: in \`$ac_pwd':" >&5
-printf "%s\n" "$as_me: error: in \`$ac_pwd':" >&2;}
-as_fn_error $? "The pkg-config script could not be found or is too old.  Make sure it
-is in your PATH or set the PKG_CONFIG environment variable to the full
-path to pkg-config.
-
-Alternatively, you may set the environment variables UDEV_CFLAGS
-and UDEV_LIBS to avoid the need to call pkg-config.
-See the pkg-config man page for more details.
-
-To get pkg-config, see <http://pkg-config.freedesktop.org/>.
-See \`config.log' for more details" "$LINENO" 5; }
+	: # libudev optional (Maestro has no udev)
 else
         UDEV_CFLAGS=$pkg_cv_UDEV_CFLAGS
         UDEV_LIBS=$pkg_cv_UDEV_LIBS
PATCH_EOF

./configure \
	--prefix=/usr \
	--build=$BUILD \
	--host=$HOST

make -j${JOBS}
make DESTDIR="$INSTALL_PATH" install
