[package]
name = "font-cursor-misc"
version = "1.0.4"
description = "X.Org bitmap font providing the default \"cursor\" font used for the X pointer."

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/font/font-cursor-misc-1.0.4.tar.xz"

[[package.dep]]
type = "build"
name = "font-util"
version = "*"

[[package.dep]]
type = "build"
name = "bdftopcf"
version = "*"

[[package.dep]]
type = "build"
name = "mkfontscale"
version = "*"

[[package.dep]]
type = "build"
name = "mkfontdir"
version = "*"

[[package.dep]]
type = "build"
name = "gzip"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
