#!/bin/bash

set -e
cd *

./config \
	--prefix=/usr         \
	--openssldir=/etc/ssl \
	--libdir=lib          \
	shared                \
	zlib-dynamic

make -j${JOBS}
make DESTDIR="$INSTALL_PATH" install
