#!/bin/bash

set -e

# Compile
# FIXME: compilation of panic_abort is required only because of a Cargo bug. remove when fixed
cargo build --bin blimp --release --target $HOST -Zbuild-std=std,panic_abort

# Install
mkdir -pv $SYSROOT/usr/{bin,lib/blimp}
cp -v target/$HOST/release/blimp $SYSROOT/usr/bin/blimp
