#!/bin/bash

set -e
cd *

# TODO use build dependencies instead
./contrib/download_prerequisites

mkdir build
cd build

mkdir -pv $HOST/libgcc
ln -s ../../../libgcc/gthr-posix.h $HOST/libgcc/gthr-default.h

# Compile
../configure --prefix=/usr \
	--build=$BUILD \
	--host=$HOST \
	--target=$TARGET \
	CC_FOR_TARGET=$TARGET-gcc \
	--with-build-sysroot=$BUILD_SYSROOT \
	--enable-initfini-array \
	--disable-nls \
	--disable-multilib \
	--disable-decimal-float \
	--disable-libatomic \
    --disable-libgomp \
    --disable-libquadmath \
    --disable-libssp \
    --disable-libvtv \
    --disable-libstdcxx \
    --enable-languages=c,c++
make -j${JOBS}

# Install
make DESTDIR=$SYSROOT install
ln -s gcc $SYSROOT/usr/bin/cc
