[package]
name = "gcc"
version = "13.2.0"
description = "The GNU Compiler Collection includes front ends for C, C++, Objective-C, Fortran, Ada, Go, and D, as well as libraries for these languages (libstdc++,...)"

[[source]]
location = "/"
url = "https://ftp.gnu.org/gnu/gcc/gcc-13.2.0/gcc-13.2.0.tar.gz"

[[package.dep]]
type = "build-and-run"
name = "linux-headers"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-libstdc++"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
