#!/bin/bash

set -e
cd *

# Compile
mkdir build
cd build
../configure --disable-bzlib --disable-libseccomp --disable-xzlib --disable-zlib
make -j${JOBS}
cd ..

./configure --prefix=/usr --host=$TARGET --build=$HOST
make FILE_COMPILE=$(pwd)/build/src/file -j${JOBS}

# Install
make DESTDIR=$SYSROOT install
