#!/bin/bash

set -e
cd *

mkdir build
cd build
../configure --disable-bzlib --disable-libseccomp --disable-xzlib --disable-zlib
make -j${JOBS}
cd ..

./configure --prefix=/usr --host=$HOST --build=$BUILD
make FILE_COMPILE=$(pwd)/build/src/file -j${JOBS}

make DESTDIR=$INSTALL_PATH install
