#!/bin/bash

set -e
cd *

mkdir build
cd build

# Compile
../configure \
	--prefix=/usr \
	--build="$BUILD" \
	--host="$HOST" \
	--target="$TARGET" \
	--enable-shared \
	--disable-werror \
	--enable-64-bit-bfd
make -j${JOBS}

# Install
make DESTDIR=$SYSROOT install -j1
install -vm755 libctf/.libs/libctf.so.0.0.0 $SYSROOT/usr/lib
