[package]
name = "mpfr"
version = "4.2.2"
description = "The MPFR library is a C library for multiple-precision floating-point computations with correct rounding."

[[source]]
location = "/"
url = "https://www.mpfr.org/mpfr-4.2.2/mpfr-4.2.2.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "gmp"
version = "6.2.1"

[[package.dep]]
type = "build"
name = "diffutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"
