#!/bin/bash

set -e
cd *

./contrib/download_prerequisites

# Patch
case ${HOST%%-*} in
	x86_64)
		sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
	;;
esac
sed '/thread_header =/s/@.*@/gthr-posix.h/' -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir build
cd build

# GCC 15's libcody assumes `u8""` literals are `char` arrays, which stopped
# being true in C++20, so it fails to build under host compilers defaulting to
# gnu++20 or later (GCC 16+). Drop `char8_t` rather than pinning the dialect:
# libcody's configure demands `__cplusplus` be exactly 201103 and retries with
# `-std=c++11`, which an explicit `-std=` here would override.
CXXFLAGS="-g -O2 -fno-char8_t" ../configure \
	--prefix="/usr"                          \
	--build="$BUILD"                         \
	--host="$HOST"                           \
	--target="$TARGET"                       \
	LDFLAGS_FOR_TARGET=-L$PWD/$TARGET/libgcc \
	--with-build-sysroot="$SYSROOT"          \
	--disable-nls                            \
	--disable-multilib                       \
	--disable-libatomic                      \
	--disable-libgomp                        \
	--disable-libquadmath                    \
	--disable-libssp                         \
	--disable-libvtv                         \
	--enable-default-pie                     \
	--enable-default-ssp                     \
	--enable-languages=c,c++                 \
	--disable-libsanitizer

make -j$JOBS
make DESTDIR="$INSTALL_PATH" install-strip
ln -sv gcc "$INSTALL_PATH/usr/bin/cc"
