#!/bin/bash

set -e
cd *

./contrib/download_prerequisites

# Patch
case ${HOST%%-*} in
	x86_64)
		sed -e '/m64=/s/lib64/lib/' -i.orig gcc/config/i386/t-linux64
	;;
esac
sed '/thread_header =/s/@.*@/gthr-posix.h/' -i libgcc/Makefile.in libstdc++-v3/include/Makefile.in

mkdir build
cd build

../configure \
	--prefix="/usr"                          \
	--build="$BUILD"                         \
	--host="$HOST"                           \
	--target="$TARGET"                       \
	LDFLAGS_FOR_TARGET=-L$PWD/$TARGET/libgcc \
	--with-build-sysroot="$SYSROOT"          \
	--disable-nls                            \
	--disable-multilib                       \
	--disable-libatomic                      \
	--disable-libgomp                        \
	--disable-libquadmath                    \
	--disable-libssp                         \
	--disable-libvtv                         \
	--enable-default-pie                     \
	--enable-default-ssp                     \
	--enable-languages=c,c++

make -j$JOBS
make DESTDIR="$INSTALL_PATH" install

ln -sv gcc "$INSTALL_PATH/usr/bin/cc"
