#!/bin/bash

set -e
cd *

./configure \
	--build="$BUILD" \
	--host="$HOST" \
	--prefix="/usr" \
	--enable-debug \
	--enable-optimize \
	--enable-shared
make -j${JOBS}

make DESTDIR=$INSTALL_PATH install
