[package]
name = "xkbcomp"
version = "1.5.0"
description = "X keyboard description compiler, used by the X server to compile keymaps from the XKB database."

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/app/xkbcomp-1.5.0.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libx11"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxkbfile"
version = "*"

[[package.dep]]
type = "build"
name = "xorgproto"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
