#!/bin/bash

set -e
cd kernel/

# TODO support other architectures
cargo build --release

cd ..
mkdir -p $SYSROOT/usr/src/maestro
cp -rv * $SYSROOT/usr/src/maestro/
chmod -R +r $SYSROOT/usr/src/maestro/
