#!/bin/bash

set -e
cd kernel/

# TODO support other architectures
cargo build --release

cd ..
mkdir -p $INSTALL_PATH/usr/src/maestro
cp -rv * $INSTALL_PATH/usr/src/maestro/
chmod -R +r $INSTALL_PATH/usr/src/maestro/
