[package]
name = "maestro-build"
version = "1.0"
description = "The Maestro kernel served with source and build files that are necessary for module compilation"

[[source]]
location = "/"
git_url = "https://github.com/maestro-os/maestro"