#!/bin/bash

set -e

# Patching to support Maestro
# TODO sed -i 's/^	gnu\* |/	gnu* | maestro* |/' config.sub

# Compiling
./configure --prefix=/usr --host=$TARGET
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT install
