[package]
name = "python"
version = "3.14.4"
description = "The Python programming language"

[[source]]
location = "/"
url = "https://www.python.org/ftp/python/3.14.4/Python-3.14.4.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "expat"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "openssl"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "findutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
