#!/bin/bash

set -e

# TODO Add a feature in the package builder to unwrap the directories automatically
cd $(ls -1d gawk*)

# Patching to support Maestro
# TODO sed -i 's/^	gnu\* |/	gnu* | maestro* |/' config.sub

# Ignoring some useless files
sed -i 's/extras//' Makefile.in

# Compiling
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT install
