#!/bin/bash

set -e
cd *

# Ignore some useless files
sed -i 's/extras//' Makefile.in

# Compile
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST
make -j${JOBS}

# Install
make DESTDIR=$SYSROOT install
