[package]
name = "libxcb"
version = "1.17.0"
description = "X protocol C-language Binding"

[[source]]
location = "/"
url = "https://www.x.org/releases/individual/lib/libxcb-1.17.0.tar.xz"

[[package.dep]]
type = "build-and-run"
name = "musl"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "libxau"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xcb-proto"
version = "*"

[[package.dep]]
type = "build-and-run"
name = "xorgproto"
version = "*"

[[package.dep]]
type = "build"
name = "bash"
version = "*"

[[package.dep]]
type = "build"
name = "coreutils"
version = "*"

[[package.dep]]
type = "build"
name = "gawk"
version = "*"

[[package.dep]]
type = "build"
name = "grep"
version = "*"

[[package.dep]]
type = "build"
name = "make"
version = "*"

[[package.dep]]
type = "build"
name = "pkgconf"
version = "*"

[[package.dep]]
type = "build"
name = "python"
version = "*"

[[package.dep]]
type = "build"
name = "sed"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-binutils"
version = "*"

[[package.dep]]
type = "build"
name = "bootstrap-gcc"
version = "*"
