#!/bin/bash

set -e
cd *

./configure --prefix=/usr \
	--host=$HOST \
	--build=$BUILD \
	--enable-install-program=hostname
make -j${JOBS}

make DESTDIR=$INSTALL_PATH install

mkdir -p $INSTALL_PATH/usr/sbin
mv $INSTALL_PATH/usr/bin/chroot $INSTALL_PATH/usr/sbin

mkdir -p $INSTALL_PATH/usr/share/man/man8
mv $INSTALL_PATH/usr/share/man/man1/chroot.1 $INSTALL_PATH/usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' $INSTALL_PATH/usr/share/man/man8/chroot.8
