#!/bin/bash

set -e
cd *

# Compile
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST \
	--enable-install-program=hostname
make -j${JOBS}

# Install
make DESTDIR=$SYSROOT install

mkdir -p $SYSROOT/usr/sbin
mv $SYSROOT/usr/bin/chroot $SYSROOT/usr/sbin

mkdir -p $SYSROOT/usr/share/man/man8
mv $SYSROOT/usr/share/man/man1/chroot.1 $SYSROOT/usr/share/man/man8/chroot.8
sed -i 's/"1"/"8"/' $SYSROOT/usr/share/man/man8/chroot.8
