#!/bin/bash

set -e
cd *

unset CFLAGS LDFLAGS

case ${HOST%%-*} in
	i[3456]86)
		ARCH=i386
		;;
	x86_64)
		ARCH=x86_64
		;;
	*)
		>&2 echo "Unsupported architecture '$ARCH'"
		exit 1
		;;
esac

make headers_install ARCH=$ARCH INSTALL_HDR_PATH="$INSTALL_PATH/usr"
