#!/bin/bash

set -e

# TODO Add a feature in the package builder to unwrap the directories automatically
cd $(ls -1d bash*)

# Patching to support Maestro
# TODO sed -i 's/^	gnu\* |/	gnu* | maestro* |/' config.sub

# Compiling
./configure --prefix=/usr \
	--host=$TARGET \
	--build=$HOST \
	--without-bash-malloc
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT install
ln -s bash $SYSROOT/usr/bin/sh
