#!/bin/bash

set -e

# Compiling
./configure --prefix=/ \
	--host=$TARGET \
	--build=$HOST \
	--without-bash-malloc
make -j${JOBS}

# Installing
make DESTDIR=$SYSROOT install
ln -sv bash $SYSROOT/bin/sh
